### ISSUE TITLE
Selected (meta-)relations and their member objects not demarcated clearly enough.

### ISSUE THREAD

**Issue by yrammos** [DCMLab/reductive_analysis_app#54] opened 2021-03-10 22:37 UTC
This is in contrast to secondary note-heads, which correctly appear green.

**Comment by yrammos** [comment] 2021-03-10 22:50
Duplicate of #11, actually.

**Comment by pettter** [comment] 2021-03-11 12:10
I think you mean that #53 is a duplicate of #11, not this one?

**Comment by pettter** [comment] 2021-03-11 12:13
In regards to the actual issue - this stems from secondaries being "greyed out" using transparency rather than color, so the filter "shines through". This can be visible if a note is both primary and secondary on hovering over the relation where it is primary.

**Comment by yrammos** [comment] 2021-03-12 08:56
This is the case indeed. The effect is manifest also in reductions (new views), in which the note *appears* only in its role as primary. The usability problem is more acute with long-range relations in non-reduced views.

I'll look into it.

**Comment by yrammos** [comment] 2021-03-12 09:08
Changing the issue title to include a set of potential related improvements:

- [ ] Use red fill for notes that are primary in the currently hovered-on relation (regardless of their role in other relations).
- [ ] Outline the currently selected (meta-)relation for enhanced visibility. (See #56)
- [ ] Outline the member relations of the currently selected meta-relation.

**Closed** 2021-03-15 15:41 UTC
Labels: bug, ui
